### ISSUE TITLE
compile error (Linux)

### ISSUE THREAD

**Issue by tissatussa** [ehsanrashid/DON#8]
hi,

I use Ubuntu 20.04.1 and can NOT compile DON .. i tried to use the (default) GCC compiler and also CLANG but they both give errors .. see terminal log text in ZIP file 

[don_compile_errors.zip](https://github.com/ehsanrashid/DON/files/5548699/don_compile_errors.zip)

BTW. in /src/nnue/architectures/ i also had to rename  halfkp_256x2-32-32.h  to  HalfKP_256x2-32-32.h  (watch the capitals) because this gave an error also ..

**Comment by ehsanrashid** [comment]
@tissatussa  the issue has been resolved please check the latest code.

I let me know if you got issue again?

**Comment by tissatussa** [comment]
I just compiled your newest version but i still have some errors :
[don_compile_errors_B.zip](https://github.com/ehsanrashid/DON/files/5649533/don_compile_errors_B.zip)
this log also shows again i first had to rename that .h file in /architectures ..
HTH

**Comment by ehsanrashid** [comment]
@tissatussa .. now the issue in the above files are resolved.

**Comment by ehsanrashid** [comment]
@tissatussa  can you compile the latest code.?

Thanks in advance

**Comment by tissatussa** [comment]
thanks for your support! Today i compiled your newest version but i still have an error, see attached ZIP with the terminal log.

[DON-master_C_log.zip](https://github.com/ehsanrashid/DON/files/5655352/DON-master_C_log.zip)


I'm not a beginner at computers and linux, how can i help you to solve the issue?  With Meld (a linux diff GUI) i see you changed the name of that .h file in /architectures, so i did not have to rename it. And at line 57 in bitboard.cpp you added "noexcept". However, the log shows 1 error and the compilation ended :

evaluator.cpp:364:68: internal compiler error: unexpected expression ‘std::clamp’ of kind overload [...]

**Comment by ehsanrashid** [comment]
@tissatussa .. now the issue in the above files are resolved.

**Comment by tissatussa** [comment]
i just downloaded your newest source ZIP and compiled it, but i still have the SAME error .. see my DON-master_C_log.zip .. I also did a diff compare of these newest source files (my "D") and the previous ones (my "C") : i see you made some changes in the files searcher.cpp and type.h .. and you did not change any code in evaluator.cpp, where the error seems to be ? :

![Screenshot_2020-12-12_09-39-08](https://user-images.githubusercontent.com/1109281/101979596-a2272980-3c5e-11eb-86b1-988160cc848d.png)

to me it looks like some bracket is wrong, but i'm not a C-language programmer .. i still want to help you, to solve the issue and i patiently await your newest code !

**Comment by tissatussa** [comment]
hi,
after some time i downloaded your newest DON and compiled it, but it still gives an error ..

in terminal i get this message, and i read the README but i have no clue what to do :

_Please submit a full bug report,
with preprocessed source if appropriate.
See /usr/share/doc/gcc-9/README.Bugs for instructions._

here is my terminal output :

# make build ARCH=x86-64-modern
Default net: nn-62ef826d1a6d.nnue
Downloading https://tests.stockfishchess.org/api/nn/nn-62ef826d1a6d.nnue

Config:
---------
debug   : 'no'
sanitize: 'no'
optimize: 'yes'
arch    : 'x86_64'
comp    : 'gcc'
bits    : '64'
kernel  : 'Linux'
os      : 'GNU/Linux'
prefetch: 'yes'
popcnt  : 'yes'
sse     : 'yes'
mmx     : 'no'
sse2    : 'yes'
ssse3   : 'yes'
sse41   : 'yes'
avx2    : 'no'
bmi2    : 'no'
avx512  : 'no'
vnni256 : 'no'
vnni512 : 'no'
neon    : 'no'

Flags:
---------
CXX     : g++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto
LDFLAGS :  -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -flto=jobserver

Testing config sanity. If this fails, try 'make help' ...

make ARCH=x86-64-modern COMP=gcc all
make[1]: Entering directory '/home/roelof/Downloads/DON-master/src'
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o main.o main.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o bitbase.o bitbase.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o bitboard.o bitboard.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o cuckoo.o cuckoo.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o endgame.o endgame.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++17  -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o evaluator.o evaluator.cpp
evaluator.cpp: In member function ‘void Evaluator::{anonymous}::Evaluation<Trace>::initialize()’:
evaluator.cpp:364:68: internal compiler error: unexpected expression ‘std::clamp’ of kind overload
  364 |                            std::clamp(sRank(kSq), RANK_2, RANK_7)) };
      |                                                                    ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make[1]: *** [<builtin>: evaluator.o] Error 1
make[1]: Leaving directory '/home/roelof/Downloads/DON-master/src'
make: *** [Makefile:752: build] Error 2

**Comment by ehsanrashid** [comment]
> hi,
> after some time i downloaded your newest DON and compiled it, but it still gives an error ..
> 
> in terminal i get this message, and i read the README but i have no clue what to do :
> 
> _Please submit a full bug report, with preprocessed source if appropriate. See /usr/share/doc/gcc-9/README.Bugs for instructions._
> 
> here is my terminal output.
> NOTE: this issue-editor does not correctly show the pasted text .. at the error we see a '^' which points to the last '}' of the concerning code line.
> 
> # make build ARCH=x86-64-modern
> Default net: nn-62ef826d1a6d.nnue
> Downloading https://tests.stockfishchess.org/api/nn/nn-62ef826d1a6d.nnue
> 
> ## Config:
> debug : 'no'
> sanitize: 'no'
> optimize: 'yes'
> arch : 'x86_64'
> comp : 'gcc'
> bits : '64'
> kernel : 'Linux'
> os : 'GNU/Linux'
> prefetch: 'yes'
> popcnt : 'yes'
> sse : 'yes'
> mmx : 'no'
> sse2 : 'yes'
> ssse3 : 'yes'
> sse41 : 'yes'
> avx2 : 'no'
> bmi2 : 'no'
> avx512 : 'no'
> vnni256 : 'no'
> vnni512 : 'no'
> neon : 'no'
> 
> ## Flags:
> CXX : g++
> CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto
> LDFLAGS : -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -flto=jobserver
> 
> Testing config sanity. If this fails, try 'make help' ...
> 
> make ARCH=x86-64-modern COMP=gcc all
> make[1]: Entering directory '/home/roelof/Downloads/DON-master/src'
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o main.o main.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o bitbase.o bitbase.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o bitboard.o bitboard.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o cuckoo.o cuckoo.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o endgame.o endgame.cpp
> g++ -Wall -Wcast-qual -fno-exceptions -std=c++17 -Wextra -Wshadow -pedantic -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -DUSE_PREFETCH -msse -DUSE_POPCNT -msse3 -mpopcnt -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -c -o evaluator.o evaluator.cpp
> evaluator.cpp: In member function ‘void Evaluator::{anonymous}::Evaluation::initialize()’:
> evaluator.cpp:364:68: internal compiler error: unexpected expression ‘std::clamp’ of kind overload
> 364 | std::clamp(sRank(kSq), RANK_2, RANK_7)) };
> | ^
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See file:///usr/share/doc/gcc-9/README.Bugs for instructions.
> make[1]: *** [: evaluator.o] Error 1
> make[1]: Leaving directory '/home/roelof/Downloads/DON-master/src'
> make: *** [Makefile:752: build] Error 2

please now try new version

thanks

**Comment by ehsanrashid** [comment]
@tissatussa please try new version it will compile.

Thanks

**Comment by tissatussa** [comment]
i still have the error (all my previous config lines are the same) :

![Screenshot_2021-04-08_12-30-47](https://user-images.githubusercontent.com/1109281/114012481-a65b0080-9866-11eb-9404-d0389e9e19ae.png)

**Comment by ehsanrashid** [comment]
i have changed the code it is comipling on my side with new c++17 compiler
@tissatussa

**Comment by tissatussa** [comment]
sorry, i still have the error .. I have Xubuntu 20.04 and it comes with default gcc version 9.3.0 :

$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.

on https://ducciogasparri.it/2020/07/30/installing-c17-and-c20-on-ubuntu-and-amazon-linux/ i find it's possible to update gcc to gcc-10, but i have to manually switch libraries .. then i can do c++17 (and c++20 !?) .. so i found https://linuxize.com/post/how-to-install-gcc-on-ubuntu-20-04/ and i used the update-alternatives command .. now my active version is changed indeed :

$ gcc --version
gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.

but DON does still not compile, see error below :

![Screenshot_2021-04-08_13-29-12](https://user-images.githubusercontent.com/1109281/114019548-d6a69d00-986e-11eb-83d3-f47c0c17fd07.png)

in the DON makefile i also tried to change "-std=c++17" into "-std=c++20" (as the article suggested), but a fatal error remains ..

**Comment by ehsanrashid** [comment]
@tissatussa yes issue has been fix also.
Try checking my new code.

thanks

**Comment by ehsanrashid** [comment]
@tissatussa it was a error on Linux but was fine on windows.
I push the fix code in repo..

try my new code.

thanks

**Comment by tissatussa** [comment]
now i have different errors : see attached PDF :
[don_errors.pdf](https://github.com/ehsanrashid/DON/files/6280156/don_errors.pdf)

**Comment by ehsanrashid** [comment]
@tissatussa  now check the latest code.. it has been fixed

**Comment by tissatussa** [comment]
=================================
*            SUCCESS            *
=================================

**Comment by tissatussa** [comment]
At last we managed to compile DON on Linux !  I learned something about different versions of GCC next to eachother ..

**Comment by ehsanrashid** [comment]
@tissatussa check the latest version i have some new fix also.. hopefully it will compiler for AVX512 also.

thanks

**Comment by tissatussa** [comment]
how can i receive an automatic message from GitHub when you (or any other GitHub programmer) makes an update to the master ?  I clicked the "Follow" button but it does not seem to work .. about any new version : can you give DON some version numer ?  Now only the date is mentioned with 'uci' command .. Regarding AVX512 : i can not test this, sorry ..

thanks and good luck !

**Comment by tissatussa** [comment]
hi, i just compiled your 210408 version and let (by using CuteChess) it play against ShashChess, the strongest engine i know (some special SF fork) -- i gave this start FEN to test engines in closed positions :

r1bqkb1r/pp3ppp/2np1n2/2p1p3/4P3/2N3PP/PPPP1PB1/R1BQK1NR w KQkq - 0 6



White to move. DON plays Black. The center is closed in an early stage, both players can try a pawn break, but some long term planning is needed : where to develop the pieces ? In this game White offers the Ra1 for Blacks' black-squared Bishop (the 'general') and gets a wild attack with a Knight.

also see this video about it, which i made this evening :
**chess : forget her**
https://www.bitchute.com/video/5OvdJh1YYzRy/

so DON lost a nice game, but with White it played very well against ShashChess in this position, both engines evaluating 0.00 until around move 40 !

**Comment by ehsanrashid** [comment]
@tissatussa please give me your gmail address or any mobile contact.
So that i will update you if new changes.
